### ISSUE TITLE
Add ci.yml workflow to modules

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-ci#11]
### ACs
- [x] Add workflow to all supported silverstripe modules to use ci.yml - NOTE: this needs to target the oldest supported branches and be merged-up, not just the default branches
- [x] Best effort to maintain any custom logic within .travis.yml files
- [x] Maintain travis ci support for a while to validate things work as expected
- [x] Update all module readme status badges from travis-ci to github actions default branch
- [x] Ensure workflows do not run on forks, or at least scheduled workflows do not run on forks
- [ ] Workflows are green

### ACs Round 2 PRs
- [ ] Remove .travis.yml files
- [ ] In ci.yml and keepalive.yml (and readmes gha-ci, gha-keepalive and gha-update-js) change `startsWith(github.repository, '<account>/')` to `github.repository_owner == '<account>'`
- [ ] Some travis badges were not updated e.g. silvestripe/silversripe-postgresql - the initial `$find` in module-standardiser was too strict
- [ ] Remove travis badges and add new CI badges to https://github.com/silverstripe/supported-modules
  - [ ] Use the updated table to populate the supported modules table in silverstripe.org

### Notes
- Usually makes more sense to just hardcode things in ci.yml rather than trying to make ci.yml move configurable
- Workarounds to make workflows not run on forks - https://github.com/microsoft/TypeScript/pull/48693/files - https://github.community/t/do-not-run-cron-workflows-in-forks/17636
- When creating a pull-request to add ci.yml to a repo, it will run on pull-request BUT ONLY if there are free github action worker available. It will not queue the workflow like you would expect. This is certainly inconvenient.
- I have validated that account that have maxed out their github actions workers will still queue up ci runs, provided there is a ci.yml defined on the repo - i.e. you cannot bypass ci.yml by just spamming pull-requests. Test [here](https://github.com/emteknetnz/recipe-kitchen-sink/pull/3).

### Custom .travis files
- [x] ~~assets - PHP_COVERAGE_SUITE=assets .. to stop travis timing out after 10 minutes~~ not required
- [x] graphql (both 3 & 4)
- [x] framework - custom matrix cos phpcoverage was giving weird results on travis
- [x] auditor - mfa + session_manager custom

### Custom .travis files, though probably does not need to be custom
- [x] recipe-core - requires themes simple + admin + versioned - but there's no behat
- [x] vendor-plugin - may work out of the box with ci.yml
- [x] sharedraftcontent
- [x] userforms
- [x] spellcheck - apt packages (ci.yml has this hardcoded)

### Graphql3
- [x] Graphql4 will install by default
- [x] Add explicitly add a graphql3 behat 'extra_job' for asset-admin, versioned-admin and elemental

### missing .travis.yml / ancient non-shared .travis
- [x] mink-facebook-web-driver (only unit testing thing in vendor folder, should probably just remove)
- [x] recipe-plugin (no current CI, no unit tests)
- [x] recipe-testing (no current CI, no unit tests, no code)
- [x] serve (has unit tests)
- [x] testsession (no current CI, no unit tests)

### .travis files where REQUIRE_EXTRA should be moved to composer.json require-dev

~~Note: keep silverstripe/frameworktest as a requirement in module ci.yml, rather than composer require-dev, because it should eventually get split to move the 'behat test models' to a separate module - [issue](https://github.com/silverstripe/silverstripe-framework/issues/9712). If/when that happens, consider moving the requirement of the new module to require-dev~~

- [x] elemental-bannerblock require elemental
- [x] recipe-form-building - requies gridfieldqueuedexport + queuedjobs
- [x] blog - requires widgets, comments, content-widgets
- [x] comments - requires ezyang/htmlpurifier
- [x] contentreview - requires symbiote/silverstripe-queuedjobs
- [x] externallinks - requires symbiote/silverstripe-queuedjobs
- [x] fulltextsearch - requires queuedjobs and subsites
- [x] recipe-blog - requires gridfieldqueuedexport, queuedjobs
- [x] reciple-ccl - requires versioned
- [x] recipe-solr-search - requires cwp/cwp, cwp/cwp-core, cwp starter theme
- [x] securityreport - requires subsites
- [x] sitewidgecontent-report - requies subsites, taxonomy, contentreview
- [x] totp-authenticator - requires webautn-authenticator - other things are sorted in ci.yml

### PRs - CI
- https://github.com/silverstripe/gha-generate-matrix/pull/3
- https://github.com/silverstripe/gha-ci/pull/20
- https://github.com/silverstripe/gha-generate-matrix/pull/5
- https://github.com/silverstripe/silverstripe-framework/pull/10360
- https://github.com/silverstripe/gha-generate-matrix/pull/6
- https://github.com/silverstripe/gha-ci/pull/23
- https://github.com/silverstripe/gha-generate-matrix/pull/7
- https://github.com/silverstripe/gha-generate-matrix/pull/8
- https://github.com/silverstripe/gha-ci/pull/24
- https://github.com/silverstripe/gha-generate-matrix/pull/10
- https://github.com/silverstripe/gha-ci/pull/22
- https://github.com/silverstripe/gha-update-js/pull/4
- https://github.com/silverstripe/gha-keepalive/pull/4
- https://github.com/silverstripe/silverstripe-frameworktest/pull/109
- https://github.com/silverstripe/gha-ci/pull/26
- https://github.com/silverstripe/silverstripe-graphql/pull/483
- https://github.com/silverstripe/gha-ci/pull/27
- https://github.com/silverstripe/gha-ci/pull/29
- https://github.com/silverstripe/gha-run-tests/pull/3
- https://github.com/silverstripe/gha-generate-matrix/pull/13
- https://github.com/silverstripe/gha-ci/pull/31
- https://github.com/silverstripe/gha-generate-matrix/pull/14
- https://github.com/silverstripe/gha-ci/pull/32
- https://github.com/silverstripe/gha-ci/pull/34

### PRs - Modules
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/241
- https://github.com/silverstripe/silverstripe-versioned/pull/365
- https://github.com/silverstripe/silverstripe-siteconfig/pull/122
- https://github.com/silverstripe/silverstripe-reports/pull/149
- https://github.com/silverstripe/silverstripe-tagfield/pull/213
- https://github.com/silverstripe/comment-notifications/pull/45
- https://github.com/silverstripe/cwp/pull/310
- https://github.com/silverstripe/cwp-pdfexport/pull/25
- https://github.com/silverstripe/cwp-search/pull/44
- https://github.com/silverstripe/cwp-starter-theme/pull/210
- https://github.com/silverstripe/cwp-watea-theme/pull/148
- https://github.com/silverstripe/silverstripe-simple/pull/70
- https://github.com/silverstripe/doorman/pull/41
- https://github.com/silverstripe/silverstripe-serve/pull/32
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/43
- https://github.com/silverstripe/webpack-config/pull/50
- https://github.com/silverstripe/silverstripe-akismet/pull/42
- https://github.com/silverstripe/silverstripe-auditor/pull/44
- https://github.com/silverstripe/silverstripe-admin/pull/1319
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1277
- https://github.com/silverstripe/silverstripe-assets/pull/500
- https://github.com/silverstripe/silverstripe-blog/pull/680
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/235
- https://github.com/silverstripe/silverstripe-ckan-registry/pull/269
- https://github.com/silverstripe/silverstripe-cms/pull/2745
- https://github.com/silverstripe/silverstripe-config/pull/61
- https://github.com/silverstripe/silverstripe-errorpage/pull/68
- https://github.com/silverstripe/silverstripe-graphql/pull/481 (graphql 3)
- https://github.com/silverstripe/silverstripe-graphql/pull/482 (graphql 4)
- https://github.com/silverstripe/silverstripe-comments/pull/342
- https://github.com/silverstripe/silverstripe-content-widget/pull/31
- https://github.com/silverstripe/silverstripe-contentreview/pull/165
- https://github.com/silverstripe/silverstripe-crontask/pull/67
- https://github.com/silverstripe/silverstripe-documentconverter/pull/31
- https://github.com/silverstripe/silverstripe-elemental/pull/989
- https://github.com/silverstripe/silverstripe-userforms/pull/1156
- https://github.com/silverstripe/silverstripe-widgets/pull/191
- https://github.com/silverstripe/silverstripe-mfa/pull/459
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/95
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/115
- https://github.com/silverstripe/silverstripe-login-forms/pull/116
- https://github.com/silverstripe/silverstripe-security-extensions/pull/44
- https://github.com/silverstripe/silverstripe-upgrader/pull/200
- https://github.com/silverstripe/silverstripe-versionfeed/pull/71
- https://github.com/silverstripe/vendor-plugin/pull/54
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/462
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/345
- https://github.com/symbiote/silverstripe-multivaluefield/pull/82
- https://github.com/symbiote/silverstripe-queuedjobs/pull/378
- https://github.com/silverstripe/cow/pull/217
- https://github.com/silverstripe/eslint-config/pull/10
- https://github.com/silverstripe/MinkFacebookWebDriver/pull/19
- https://github.com/silverstripe/recipe-testing/pull/9
- https://github.com/silverstripe/silverstripe-behat-extension/pull/215
- https://github.com/silverstripe/silverstripe-postgresql/pull/130
- https://github.com/silverstripe/silverstripe-selectupload/pull/39
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/52
- https://github.com/silverstripe/recipe-ccl/pull/5
- https://github.com/silverstripe/cwp-agencyextensions/pull/74
- https://github.com/silverstripe/silverstripe-session-manager/pull/112
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/327
- https://github.com/silverstripe/silverstripe-testsession/pull/75
- https://github.com/silverstripe/recipe-solr-search/pull/11
- https://github.com/silverstripe/recipe-reporting-tools/pull/28
- https://github.com/silverstripe/recipe-form-building/pull/19
- https://github.com/silverstripe/recipe-blog/pull/33
- https://github.com/silverstripe/silverstripe-ldap/pull/41
- https://github.com/silverstripe/silverstripe-externallinks/pull/81
- https://github.com/silverstripe/silverstripe-securityreport/pull/55
- https://github.com/silverstripe/recipe-plugin/pull/23
- https://github.com/silverstripe/recipe-core/pull/73
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/67
- https://github.com/silverstripe/silverstripe-textextraction/pull/74
- https://github.com/silverstripe/silverstripe-taxonomy/pull/80
- https://github.com/silverstripe/silverstripe-subsites/pull/482
- https://github.com/silverstripe/silverstripe-spellcheck/pull/52
- https://github.com/silverstripe/silverstripe-spamprotection/pull/83
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/170
- https://github.com/silverstripe/silverstripe-segment-field/pull/67
- https://github.com/silverstripe/silverstripe-restfulserver/pull/99
- https://github.com/silverstripe/silverstripe-registry/pull/68
- https://github.com/silverstripe/recipe-services/pull/20
- https://github.com/silverstripe/recipe-content-blocks/pull/23
- https://github.com/silverstripe/recipe-collaboration/pull/17
- https://github.com/silverstripe/recipe-cms/pull/57
- https://github.com/silverstripe/recipe-authoring-tools/pull/20
- https://github.com/silverstripe/silverstripe-realme/pull/88
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/54
- https://github.com/silverstripe/silverstripe-lumberjack/pull/112
- https://github.com/silverstripe/silverstripe-iframe/pull/59
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/73
- https://github.com/silverstripe/silverstripe-html5/pull/37
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/79
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/30
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/88
- https://github.com/silverstripe/cwp-core/pull/108
- https://github.com/silverstripe/silverstripe-installer/pull/326 (do last, most issues will be in individual modules)
- https://github.com/silverstripe/recipe-kitchen-sink/pull/14 (do last, most issues will be in individual modules)

**Comment by emteknetnz** [comment]
We'll use this to create all the initial pull-requests - https://github.com/emteknetnz/module-standardiser

It creates PRs that look like this https://github.com/silverstripe/silverstripe-tagfield/pull/212

All the cron jobs are scheduled at varying times throughout the week so we don't clog things up

For any custom logic, we'll add this manually after the initial pull-requests have been created

**Comment by GuySartorelli** [comment]
Looks like a lot of [supported modules](https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list) are missing from the PR list:

- bringyourownideas/silverstripe-maintenance
- bringyourownideas/silverstripe-composer-update-checker	
- bringyourownideas/silverstripe-composer-security-checker
- colymba/gridfield-bulk-editing-tools
- cwp/cwp-core
- dnadesign/silverstripe-elemental-subsites
- dnadesign/silverstripe-elemental-userforms
- hafriedlander/phockito
- hafriedlander/silverstripe-phockito
- lekoala/silverstripe-debugbar
- silverstripe/silverstripe-activedirectory
- silverstripe/elemental-bannerblock
- silverstripe/elemental-fileblock
- silverstripe/environmentcheck
- silverstripe/externallinks
- silverstripe/fulltextsearch
- silverstripe/gridfieldqueuedexport
- silverstripe/html5
- silverstripe/hybridsessions

Probably more too - I stopped checking when I got that far.

**Comment by maxime-rainville** [comment]
Didn't quite manage to get all the builds green, but these are mostly failures that just got highlighted by the new build system. We'll create a follow up card.

**Comment by maxime-rainville** [comment]
Didn't quite manage to get all the builds green, but these are mostly failures that just got highlighted by the new build system. We'll create a follow up card.
