### ISSUE TITLE
`MNT` commit is triggering auto-tagging, but shouldn't

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-ci#111]
A release was made for `silverstripe/admin` that only included a `MNT` commit. See https://github.com/silverstripe/silverstripe-admin/releases/tag/2.1.20

`MNT` commits should not be triggering releases.

## Acceptance criteria
- The following commits do not trigger auto patching: MNT, DOC, Merge.

## PR
- https://github.com/silverstripe/gha-gauge-release/pull/10

**Comment by GuySartorelli** [comment]
PR merged, assigned to Steve to check if it worked (if there's a way to do so)

**Comment by emteknetnz** [comment]
I don't know of a way to test this short of adding random MNT commits with leading bullet points, which I don't want to do. I'll just close this and we can revisit if it turns out there's an issue in the future

**Comment by GuySartorelli** [comment]
Reopening - it's still happening. See https://github.com/tractorcow-farm/silverstripe-fluent/releases/tag/7.1.3

**Comment by emteknetnz** [comment]
Issue on the linked tag was that the commit message was multiline:

```
MNT Replace sass-lint with stylelint (#862)

sass-lint went EOL ages ago
```

Commits are parsed line by line looking for non MNT/Doc/Merge/[space] commits. If it finds a single line like this it will perform a release.

While we could only look at the first line, we'll now be NOT releases if we have a squashed PR will multiple commits where the message looks something like this

```
MNT Update workflow

FIX Important bug resolved
```

I don't really see a way around this. Either we release too much as we do now, or we risk not releasing things when they should have been released.

The downside of releasing maintainence only commits is very low, and I think it has much less downside then not releasing things that should be released

I'll close this
