### ISSUE TITLE
Double .x-dev requirements in --prefer-lowest builds

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-ci#132]
After the change in https://github.com/silverstripe/gha-ci/pull/131 there are now some invalid double .x-dev requirements e.g. `5.x-dev.x-dev` for example https://github.com/silverstripe/silverstripe-admin/actions/runs/9789724139/job/27029957813?pr=1792#step:9:355

## PR
- https://github.com/silverstripe/gha-ci/pull/133
- https://github.com/silverstripe/gha-ci/pull/134

**Comment by GuySartorelli** [comment]
PR merged
Reassigning to Steve to double check that resolved the problem

**Comment by GuySartorelli** [comment]
Still got massive prefer-lowest failures across the board.

**Comment by GuySartorelli** [comment]
PR merged
Reassigning to Steve to double check that resolved the problem

**Comment by emteknetnz** [comment]
Resolved. There are still a couple of failures, though they are actual --prefer-lowest failures rather than CI simply not running
