### ISSUE TITLE
gha-ci patch tag job broken

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-ci#149]
https://github.com/silverstripe/gha-ci/actions/runs/10498701316/job/29084137582#logs

Failed after merging https://github.com/silverstripe/gha-ci/pull/148

The repositories tag-patch-release.yml workflow uses the gha-tag-release action

For gha repos, the gha-tag-release action will dispatch the auto-tag.yml workflow on the repository. Doing this requires an `actions: write` permission on the token which is currently missing

Note that I ran module standardiser on the next-patch branches

## PRs
- https://github.com/silverstripe/module-standardiser/pull/70
- https://github.com/silverstripe/gha-action-ci/pull/17
- https://github.com/silverstripe/gha-add-pr-to-project/pull/13
- https://github.com/silverstripe/gha-auto-tag/pull/24
- https://github.com/silverstripe/gha-ci/pull/150
- https://github.com/silverstripe/gha-dispatch-ci/pull/20
- https://github.com/silverstripe/gha-generate-matrix/pull/103
- https://github.com/silverstripe/gha-issue/pull/16
- https://github.com/silverstripe/gha-keepalive/pull/18
- https://github.com/silverstripe/gha-merge-up/pull/44
- https://github.com/silverstripe/gha-pull-request/pull/18
- https://github.com/silverstripe/gha-run-tests/pull/37
- https://github.com/silverstripe/gha-tag-release/pull/29
- https://github.com/silverstripe/gha-trigger-ci/pull/12
- https://github.com/silverstripe/gha-update-js/pull/32

**Comment by GuySartorelli** [comment]
PRs merged, reassigning to Steve to double check it's working as expected
