### ISSUE TITLE
Remove guzzle 6 cow support

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-ci#30]
This [PR](https://github.com/silverstripe/gha-ci/pull/29) allowed installing cow ~2.0 which uses guzzle 6.  It should be reverted at some point.

It's entirely possible that something else (e.g. changing the PHP version of the linting job to PHP 8) will mean that dev-master is no longer installed, and instead the older 2.0.x version is installed

If we change the linting done in cow `schema:validate` (admittedly very unlikely) on dev-master, then we'll still be using the old linting logic in 2.0.x

**Comment by GuySartorelli** [comment]
We're not using cow's schema validation at all anymore.
