### ISSUE TITLE
node12 github actions are deprecated - will stop working mid 2023

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-ci#50]
https://github.com/silverstripe/silverstripe-installer/actions/runs/3220762331
Github actions is throwing some warnings at us:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

It says it'll stop working in "Summer 2023" which means june-ish

## Acceptance criteria
- [x] any action currently using node12 is updated to use the latest runner.

## Notes
- We should still be able to use older version of node for our builds. Just not for the actual runner.
- Note should be able to update the central github actions without having to update every single builds.

## PRs
- https://github.com/silverstripe/gha-ci/pull/66
- https://github.com/silverstripe/gha-update-js/pull/11
- https://github.com/silverstripe/gha-generate-matrix/pull/56

**Comment by emteknetnz** [comment]
Have merged and released all prs

**Comment by GuySartorelli** [comment]
Reopened to verify that the deprecation notices are gone

**Comment by GuySartorelli** [comment]
Deprecation notices aren't being emitted anymore
