### ISSUE TITLE
Fix Logger - silverstripe.log

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-ci#53]
Should just be a matter of changing "notice" to "info" - it worked for https://github.com/emteknetnz/silverstripe-installer/blob/pulls/4/test-depr-reroute-cms4/app/_config/logger.yml#L15 for showing deprecated warnings in silverstripe.log

I believe that is there are zero log entires, then silverstripe.log is simply not created by the Logger service, hence it never shows in artifacts

If the resulting silverstripe.log generated from "info" is too annoying and provides no values, then revert it to "notice" and leave an inline comment in bash saying 'just change this to "info" if you need this to actually do something'

### PRs
- https://github.com/silverstripe/gha-ci/pull/52

**Comment by GuySartorelli** [comment]
This is working
