### ISSUE TITLE
CI isn't working for module tags

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-ci#54]
### Modules - framework

~~`-release` branch not installing - https://github.com/silverstripe/silverstripe-framework/actions/runs/3441318809~~

`-beta1` tag not installing - https://github.com/silverstripe/silverstripe-framework/actions/runs/3441319137

Other tag not installing - https://github.com/silverstripe/silverstripe-framework/actions/runs/4042593676

### Installer
~~`-release` branch installs - https://github.com/silverstripe/silverstripe-installer/actions/runs/3441336248/jobs/5740760583~~
`-beta1` tag installs - https://github.com/silverstripe/silverstripe-installer/actions/runs/3441336653

### Acceptance criteria
- [ ] CI works for ~~-release and~~ -beta1 (and other pre-release) branches/tags for modules and installer

### Stretch goal
- [ ] CI works for stable and pre-release tags 

## Note:
CI for the `-release` branches was fixed with https://github.com/silverstripeltd/product-issues/issues/635

## PRs
- https://github.com/silverstripe/gha-ci/pull/62

**Comment by GuySartorelli** [comment]
PR was merged. Closing issue. This was fixed in https://github.com/silverstripe/.github/issues/23
