### ISSUE TITLE
The `save-state` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-ci#56]
> Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The above warning is showing in a lot of our CI runs. We should stop using deprecated `save-state`.

**Comment by maxime-rainville** [comment]
Duplicate of https://github.com/silverstripe/.github/issues/26
