### ISSUE TITLE
BEHAT tests fail to end safely

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-ci#67]
Our behat tests aren't stopping containers safely. See https://github.com/silverstripe/silverstripe-asset-admin/actions/runs/4887239565/jobs/8724358629 for an example.

Here's the output which _might_ be relevant from that job (in the "Stop containers" section), in case the log is removed:

> 2023-05-04 21:41:57+00:00 [Note] [Entrypoint]: Initializing database files
> Warning:  2023-05-04T21:41:57.046460Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> Warning:  2023-05-04T21:41:57.324474Z 0 [Warning] InnoDB: New log files created, LSN=45790
> Warning:  2023-05-04T21:41:57.419773Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
> Warning:  2023-05-04T21:41:57.475925Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 7e79def9-eac4-11ed-a6d7-0242ac120002.
> Warning:  2023-05-04T21:41:57.477418Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
> Warning:  2023-05-04T21:41:57.897368Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
> Warning:  2023-05-04T21:41:57.897441Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
> Warning:  2023-05-04T21:41:57.897940Z 0 [Warning] CA certificate ca.pem is self signed.
> Warning:  2023-05-04T21:41:57.907801Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
>  2023-05-04 21:42:00+00:00 [Note] [Entrypoint]: Database files initialized
>  2023-05-04 21:42:00+00:00 [Note] [Entrypoint]: Starting temporary server
>  2023-05-04 21:42:00+00:00 [Note] [Entrypoint]: Waiting for server startup
> Warning:  2023-05-04T21:42:01.137757Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> .....
> 2023-05-04T21:42:01.252004Z 0 [Note] InnoDB: 5.7.42 started; log sequence number 2766912
>  2023-05-04T21:42:01.252881Z 0 [Note] Plugin 'FEDERATED' is disabled.
>  2023-05-04T21:42:01.258850Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
>  2023-05-04T21:42:01.258874Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
> Warning:  2023-05-04T21:42:01.258878Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
> Warning:  2023-05-04T21:42:01.258880Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
> Warning:  2023-05-04T21:42:01.259424Z 0 [Warning] CA certificate ca.pem is self signed.
>  2023-05-04T21:42:01.259463Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
>  2023-05-04T21:42:01.259797Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
>  2023-05-04T21:42:01.261271Z 0 [Note] InnoDB: Buffer pool(s) load completed at 230504 21:42:01
> Warning:  2023-05-04T21:42:01.270446Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
>  2023-05-04T21:42:01.277860Z 0 [Note] Event Scheduler: Loaded 0 events
> ........
>   Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
>  Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
>  Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
>  Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
>  Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
>  2023-05-04 21:42:03+00:00 [Note] [Entrypoint]: Creating database SS_mysite
> .............
> 2023-05-04 21:42:05+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
>  
> Warning:  2023-05-04T21:42:06.189831Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
>  2023-05-04T21:42:06.191168Z 0 [Note] mysqld (mysqld 5.7.42) starting as process 1 ...
> ........
> 2023-05-04T21:42:06.272026Z 0 [Note] InnoDB: Buffer pool(s) load completed at 230504 21:42:06
>  2023-05-04T21:42:06.279772Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
>  2023-05-04T21:42:06.279787Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
> Warning:  2023-05-04T21:42:06.279791Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
> Warning:  2023-05-04T21:42:06.279793Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
> Warning:  2023-05-04T21:42:06.280329Z 0 [Warning] CA certificate ca.pem is self signed.
>  2023-05-04T21:42:06.280359Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
>  2023-05-04T21:42:06.280633Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
>  2023-05-04T21:42:06.280662Z 0 [Note] IPv6 is available.
>  2023-05-04T21:42:06.280672Z 0 [Note]   - '::' resolves to '::';
>  2023-05-04T21:42:06.280687Z 0 [Note] Server socket created on IP: '::'.
> Warning:  2023-05-04T21:42:06.281663Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
>  2023-05-04T21:42:06.288748Z 0 [Note] Event Scheduler: Loaded 0 events
> 2023-05-04T21:42:06.289478Z 0 [Note] mysqld: ready for connections.
>  Version: '5.7.42'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
>  2023-05-04T21:42:06.779912Z 2 [Note] Access denied for user 'root'@'localhost' (using password: NO)
>  2023-05-04T21:42:16.887704Z 3 [Note] Access denied for user 'root'@'localhost' (using password: NO)
>  2023-05-04T21:42:26.957482Z 4 [Note] Access denied for user 'root'@'localhost' (using password: NO)
> ... that error repeats a few more times
> Stop and remove container: c655322f95044ea98c506d2698f4c147_mysql57_7aeb6e
> /usr/bin/docker rm --force a00c2b06c181244c1f6c34f6772a09e2a12a3cfb0c6a71150baef3c128bba83f
> a00c2b06c181244c1f6c34f6772a09e2a12a3cfb0c6a71150baef3c128bba83f
> Print service container logs: 509ac507163d4f5ca8004212eb6ae177_mysql80_462b3e
> /usr/bin/docker logs --details 9e05d60c08688267ce7f5a336a8240582edae7ecad5c8e19c686953d6af238e9
>  2023-05-04 21:42:09+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.33-1.el8 started.
> Warning:  2023-05-04T21:42:09.409447Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
>  2023-05-04T21:42:09.409543Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.33) initializing of server in progress as process 79
>  2023-05-04T21:42:09.415771Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
>  2023-05-04T21:42:09.763857Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
> Warning:  2023-05-04T21:42:10.933759Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
> Warning:  2023-05-04T21:42:14.227124Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
>  2023-05-04T21:42:14.229103Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.33) starting as process 121
>  2023-05-04T21:42:14.242714Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
>  2023-05-04T21:42:14.551245Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
> Warning:  2023-05-04T21:42:14.824803Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
>  2023-05-04T21:42:14.824887Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
> Warning:  2023-05-04T21:42:14.826532Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
>  2023-05-04T21:42:14.843252Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.33'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
> 2023-05-04T21:42:14.843526Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
>  Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
>  Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
>  Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
>  Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
>  Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
>  Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
>  2023-05-04T21:42:16.902522Z 11 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.33).
>  2023-05-04T21:42:18.265487Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.33)  MySQL Community Server - GPL.
> Warning:  2023-05-04T21:42:19.198110Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
>  2023-05-04T21:42:19.199430Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.33) starting as process 1
>  2023-05-04T21:42:19.205964Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
>  2023-05-04T21:42:19.556766Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
> Warning:  2023-05-04T21:42:19.795178Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
>  2023-05-04T21:42:19.795228Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
> Warning:  2023-05-04T21:42:19.796600Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
>  2023-05-04T21:42:19.825370Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
> .........
> waiting for server to start....2023-05-04 21:42:20.907 UTC [47] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
>  2023-05-04 21:42:20.908 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
>  2023-05-04 21:42:20.911 UTC [50] LOG:  database system was shut down at 2023-05-04 21:42:20 UTC
>  2023-05-04 21:42:21.152 UTC [1] LOG:  listening on IPv6 address "::", port 5432
>  2023-05-04 21:42:21.153 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
>  2023-05-04 21:42:21.156 UTC [61] LOG:  database system was shut down at 2023-05-04 21:42:21 UTC
>  2023-05-04 21:42:21.160 UTC [1] LOG:  database system is ready to accept connections
>  2023-05-04 21:42:30.195 UTC [73] FATAL:  role "root" does not exist
>  2023-05-04 21:42:40.293 UTC [81] FATAL:  role "root" does not exist
>  2023-05-04 21:42:50.392 UTC [90] FATAL:  role "root" does not exist
>  2023-05-04 21:43:00.491 UTC [99] FATAL:  role "root" does not exist
> ...... that error repeats a few more times

**Comment by maxime-rainville** [comment]
We don't think this is causing any builds to fail. The warnings seems mostly harmless.
