### ISSUE TITLE
"make_latest" setting is incorrect for tagging patch releases

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-ci#74]
The current "make_latest" setting is incorrectly marking patch releases in the 4.x release line as the "latest" release, despite having higher semver releases (i.e. stuff in the 5.x release line) available.

e.g. see https://github.com/silverstripe/silverstripe-framework/releases - the release for 4.13.11 was marked as latest despite a higher semver release being available.
![4.13.11 is marked as latest when it isn't the latest release](https://github.com/silverstripe/gha-tag-release/assets/36352093/ec935c94-48ad-4725-8ec8-564a79b4d72b)

## PRs
- https://github.com/silverstripe/gha-tag-release/pull/13

**Comment by emteknetnz** [comment]
Need to change https://github.com/silverstripe/gha-tag-release/blob/1.1/action.yml#L172 from "legacy" to "true"|"false"

Best guess is that "legacy" treats new releases on older majors as the "latest" which is not our interpretation

We'll need to work this out manually - make an additional API in gha-tag-release that call the tags endpoint and does something similar to https://github.com/silverstripe/gha-ci/blob/1.4/.github/workflows/ci.yml#L815 to work out what the highest stable tag is, and the new tag would be newer than that, either a higher minor version or just a higher patch version

**Comment by GuySartorelli** [comment]
PR merged and action tagged.
