### ISSUE TITLE
dev/build, .env file creation, and other steps are performed when not needed

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-ci#97]
Some of our repositories use this CI for convenience, but don't need a running Silverstripe CMS project.

When installer is not included, we shouldn't be setting up a database/etc.

At best this is unnecessary work, at worst it causes failures like https://github.com/creative-commoners/silverstripe-standards/actions/runs/7688362062/job/20949498104

## PRs
- https://github.com/silverstripe/gha-generate-matrix/pull/77
- https://github.com/silverstripe/gha-ci/pull/98
- https://github.com/silverstripe/gha-ci/pull/99
- https://github.com/silverstripe/gha-generate-matrix/pull/78
- https://github.com/silverstripe/gha-generate-matrix/pull/79

**Comment by emteknetnz** [comment]
@GuySartorelli I left a comment on the merged PR to re-trigger some jobs to check things still work as expected. Once you've validated this close this issue

**Comment by GuySartorelli** [comment]
CI runs to validate this works post merge:
- https://github.com/silverstripe/vendor-plugin/actions/runs/7689373024
- https://github.com/creative-commoners/silverstripe-standards/actions/runs/7688920408
- https://github.com/silverstripe/silverstripe-framework/actions/runs/7689376358
- https://github.com/silverstripe/silverstripe-config/actions/runs/7689378654
- https://github.com/silverstripe/silverstripe-asset-admin/actions/runs/7689382421
- https://github.com/silverstripe/recipe-core/actions/runs/7689385193
- https://github.com/silverstripe/silverstripe-installer/actions/runs/7689388098

**Comment by emteknetnz** [comment]
@GuySartorelli Have merged latest PR, please re-run something to validate things still work correctly

**Comment by GuySartorelli** [comment]
Working as expected now
